// Scripted HumanView fixtures for the screenshot harness. Shapes follow
// docs/ARCHITECTURE.md §6 exactly — these are hand-authored examples of what
// the real backend would send, never generated by any game logic here.
//
// Persona names are original and Hermes-flavoured (Vex / Juniper / Ferro) —
// Hermes is the only agent platform this product shows, so fixtures never
// use another agent product's name. Model labels are neutral
// ("hermes-4-405b", "default model") for the same reason.

const now = () => Date.now() / 1000

const baseSeats = () => [
  {
    seat: 0,
    kind: 'human',
    name: 'You',
    avatar: '🧑',
    personality: null,
    model_label: null,
    stack: 870,
    committed: 20,
    total_in_pot: 60,
    state: 'active',
    hole: ['Ks', 'Kd'],
    hand_label: null,
    agent: null,
    last_action: { kind: 'call', to: 20, fallback: false },
    talk: null,
    stats: null
  },
  {
    seat: 1,
    kind: 'hermes',
    name: 'Vex',
    avatar: '🦊',
    personality: 'aggressive',
    model_label: 'hermes-4-405b',
    stack: 640,
    committed: 20,
    total_in_pot: 20,
    state: 'active',
    hole: null,
    hand_label: null,
    agent: { state: 'idle', since: null, last_error: null, tokens: { input: 4210, output: 380, total: 4590 }, decisions: 14, fallbacks: 1 },
    last_action: { kind: 'call', to: 20, fallback: false },
    talk: "Let's see some action.",
    stats: { hands: 14, vpip: 0.57, pfr: 0.36, af: 2.8 }
  },
  {
    seat: 2,
    kind: 'hermes',
    name: 'Juniper',
    avatar: '🦉',
    personality: 'cautious',
    model_label: 'default model',
    stack: 1120,
    committed: 10,
    total_in_pot: 10,
    state: 'active',
    hole: null,
    hand_label: null,
    agent: { state: 'thinking', since: now() - 4, last_error: null, tokens: { input: 2100, output: 190, total: 2290 }, decisions: 13, fallbacks: 0 },
    last_action: { kind: 'call', to: 10, fallback: false },
    talk: null,
    stats: { hands: 13, vpip: 0.22, pfr: 0.15, af: 1.1 }
  },
  {
    seat: 3,
    kind: 'test_bot',
    name: 'Sandbox',
    avatar: '🧪',
    personality: 'balanced',
    model_label: null,
    stack: 1000,
    committed: 0,
    total_in_pot: 0,
    state: 'active',
    hole: null,
    hand_label: null,
    agent: { state: 'idle', since: null, last_error: null, tokens: { input: 0, output: 0, total: 0 }, decisions: 0, fallbacks: 0 },
    last_action: null,
    talk: null,
    stats: { hands: 0, vpip: null, pfr: null, af: null }
  }
]

function base(overrides = {}) {
  return {
    schema: 1,
    table_id: 'harness-table',
    version: 42,
    status: 'running',
    pause_reason: null,
    hand_no: 7,
    button: 3,
    blinds: { sb: 5, bb: 10 },
    street: 'preflop',
    board: [],
    pots: [{ amount: 60, eligible: [0, 1, 2, 3] }],
    total_pot: 60,
    to_act: 2,
    turn_id: 'turn-abc',
    turn_started_at: now() - 4,
    turn_deadline_at: now() + 16,
    next_hand_at: null,
    seats: baseSeats(),
    legal: null,
    log: [
      { type: 'hand_start', hand_no: 7 },
      { type: 'blinds' },
      { seat: 0, type: 'action', kind: 'call', to: 20 },
      { seat: 1, type: 'action', kind: 'call', to: 20 }
    ],
    last_hand: null,
    chat: [
      { id: 'c1', kind: 'system', seat: null, text: 'Table is live. Your turn and agent connection issues will appear here.', level: 'info', at: now() - 30 },
      { id: 'c2', kind: 'human', seat: 0, text: 'Ready to lose?', level: 'info', at: now() - 20 },
      { id: 'c3', kind: 'agent', seat: 1, text: 'That hesitation is getting expensive.', level: 'info', at: now() - 15 },
      { id: 'c4', kind: 'agent', seat: 2, text: 'Patience pays. Usually yours pays me.', level: 'info', at: now() - 10 },
      { id: 'c5', kind: 'system', seat: null, text: 'Your turn. Choose an action below the table.', level: 'attention', at: now() - 2 }
    ],
    settings: { decision_timeout_s: 20, next_hand_delay_s: 4, chatter: true },
    ...overrides
  }
}

const LEGAL_HUMAN_PREFLOP = {
  seat: 0,
  to_call: 0,
  can_fold: true,
  can_check: true,
  can_call: false,
  call_amount: 0,
  raise_kind: 'raise',
  min_to: 40,
  max_to: 870,
  all_in_to: 870,
  stack: 870,
  current_bet: 20,
  committed: 20
}

export const FIXTURES = {
  setup: null, // handled specially: status 'setup'

  preflop_turn: base({
    street: 'preflop',
    to_act: 0,
    legal: LEGAL_HUMAN_PREFLOP,
    turn_started_at: now() - 2,
    turn_deadline_at: now() + 18
  }),

  agent_thinking: base({
    street: 'preflop',
    to_act: 2,
    legal: null,
    turn_started_at: now() - 7,
    turn_deadline_at: now() + 13
  }),

  flop_sidepots: base(
    (() => {
      const seats = baseSeats()
      seats[0] = { ...seats[0], stack: 0, committed: 400, total_in_pot: 400, state: 'all_in', hole: ['Ks', 'Kd'] }
      seats[1] = { ...seats[1], stack: 300, committed: 300, total_in_pot: 300, state: 'active' }
      seats[2] = { ...seats[2], stack: 0, committed: 220, total_in_pot: 220, state: 'all_in', agent: { ...seats[2].agent, state: 'idle' } }
      seats[3] = { ...seats[3], state: 'folded' }
      return {
        street: 'flop',
        board: ['Ah', 'Td', '7c'],
        pots: [
          { amount: 660, eligible: [0, 1, 2] },
          { amount: 160, eligible: [0, 1] }
        ],
        total_pot: 820,
        seats,
        to_act: 1,
        legal: null
      }
    })()
  ),

  showdown: base(
    (() => {
      const seats = baseSeats()
      seats[0] = { ...seats[0], hole: ['Ks', 'Kd'], hand_label: 'Two Pair, Kings and Sevens', state: 'active' }
      seats[1] = { ...seats[1], hole: ['Ah', 'Qh'], hand_label: 'Pair of Aces', state: 'active', talk: 'Close one!' }
      seats[2] = { ...seats[2], state: 'folded', agent: { ...seats[2].agent, state: 'idle' } }
      seats[3] = { ...seats[3], state: 'folded' }
      return {
        street: 'complete',
        board: ['Ah', 'Td', '7c', '2s', '9h'],
        pots: [{ amount: 640, eligible: [0, 1] }],
        total_pot: 640,
        to_act: null,
        legal: null,
        seats,
        next_hand_at: now() + 3,
        log: [
          { type: 'hand_start', hand_no: 7 },
          { type: 'blinds' },
          { seat: 0, type: 'action', kind: 'call', to: 20 },
          { type: 'street', name: 'flop', board: ['Ah', 'Td', '7c'] },
          { type: 'street', name: 'turn', board: ['Ah', 'Td', '7c', '2s'] },
          { type: 'street', name: 'river', board: ['Ah', 'Td', '7c', '2s', '9h'] },
          {
            type: 'showdown',
            reveals: [
              { seat: 0, cards: ['Ks', 'Kd'], hand_label: 'Two Pair, Kings and Sevens' },
              { seat: 1, cards: ['Ah', 'Qh'], hand_label: 'Pair of Aces' }
            ]
          },
          { type: 'pot_award', pot_index: 0, amount: 640, winners: [0], split: false },
          { type: 'hand_end' }
        ],
        last_hand: { hand_no: 7, winners: [0], total_pot: 640 }
      }
    })()
  ),

  // A distinct fixture (separate from `showdown`) whose ONLY job is the
  // hand-end winner moment: glow + "+640" award callout + dimmed loser +
  // countdown-to-next-hand banner + "Next hand" button, at the table's
  // default 4-handed size.
  hand_end_winner: base(
    (() => {
      const seats = baseSeats()
      seats[0] = { ...seats[0], hole: ['Ks', 'Kd'], hand_label: 'Two Pair, Kings and Sevens', state: 'active', stack: 1510 }
      seats[1] = { ...seats[1], hole: ['Ah', 'Qh'], hand_label: 'Pair of Aces', state: 'active', talk: 'Close one!' }
      seats[2] = { ...seats[2], state: 'folded', agent: { ...seats[2].agent, state: 'idle' } }
      seats[3] = { ...seats[3], state: 'folded' }
      return {
        street: 'complete',
        board: ['Ah', 'Td', '7c', '2s', '9h'],
        pots: [{ amount: 640, eligible: [0, 1] }],
        total_pot: 0,
        to_act: null,
        legal: null,
        seats,
        next_hand_at: now() + 3.4,
        log: [
          { type: 'hand_start', hand_no: 7 },
          {
            type: 'showdown',
            reveals: [
              { seat: 0, cards: ['Ks', 'Kd'], hand_label: 'Two Pair, Kings and Sevens' },
              { seat: 1, cards: ['Ah', 'Qh'], hand_label: 'Pair of Aces' }
            ]
          },
          { type: 'pot_award', pot_index: 0, amount: 640, winners: [0], split: false },
          { type: 'hand_end' }
        ],
        last_hand: { hand_no: 7, winners: [0], total_pot: 640 }
      }
    })()
  ),

  paused: base({ status: 'paused', pause_reason: 'manual', to_act: null, legal: null }),

  restored_paused: base({
    status: 'paused',
    pause_reason: 'restored',
    to_act: null,
    legal: null,
    turn_started_at: null,
    turn_deadline_at: null
  }),

  finished: base(
    (() => {
      const seats = baseSeats().map(s => (s.seat === 0 ? { ...s, stack: 4000 } : { ...s, stack: 0, state: 'out' }))
      return { status: 'finished', to_act: null, legal: null, seats }
    })()
  ),

  fallback_disconnected: base(
    (() => {
      const seats = baseSeats()
      seats[1] = {
        ...seats[1],
        last_action: { kind: 'check', to: null, fallback: true },
        agent: { ...seats[1].agent, state: 'idle' }
      }
      seats[2] = { ...seats[2], agent: { ...seats[2].agent, state: 'disconnected', last_error: 'Provider timed out' } }
      return { seats, to_act: 0, legal: LEGAL_HUMAN_PREFLOP }
    })()
  ),

  // Honesty badge: 1 real Hermes agent + 2 clearly-labelled test bots — the
  // header must say "1 Hermes agent + 2 test bots", never "3 Hermes agents".
  two_bots_one_agent: base(
    (() => {
      const seats = baseSeats()
      seats[2] = { ...seats[2], kind: 'test_bot', name: 'Sandbox B', avatar: '🧪', model_label: null, agent: { ...seats[2].agent, state: 'idle' } }
      seats[3] = { ...seats[3], name: 'Sandbox C' }
      return { seats, to_act: 0, legal: LEGAL_HUMAN_PREFLOP }
    })()
  ),

  // Two-handed table: only the human + one Hermes agent survive. Exercises
  // the heads-up SB/BB assignment (button posts SB, acts first preflop).
  heads_up: (() => {
    const seats = [
      {
        seat: 0,
        kind: 'human',
        name: 'You',
        avatar: '🧑',
        personality: null,
        model_label: null,
        stack: 1450,
        committed: 10,
        total_in_pot: 10,
        state: 'active',
        hole: ['7h', '2c'],
        hand_label: null,
        agent: null,
        last_action: null,
        talk: null,
        stats: null
      },
      {
        seat: 1,
        kind: 'hermes',
        name: 'Ferro',
        avatar: '🐉',
        personality: 'balanced',
        model_label: 'hermes-4-70b',
        stack: 550,
        committed: 5,
        total_in_pot: 5,
        state: 'active',
        hole: null,
        hand_label: null,
        agent: { state: 'idle', since: null, last_error: null, tokens: { input: 18400, output: 1520, total: 19920 }, decisions: 41, fallbacks: 2 },
        last_action: { kind: 'raise', to: 10, fallback: false },
        talk: "Heads up. Let's go.",
        stats: { hands: 41, vpip: 0.61, pfr: 0.44, af: 3.2 }
      }
    ]
    return {
      schema: 1,
      table_id: 'harness-table',
      version: 88,
      status: 'running',
      pause_reason: null,
      hand_no: 19,
      button: 0,
      blinds: { sb: 5, bb: 10 },
      street: 'preflop',
      board: [],
      pots: [{ amount: 15, eligible: [0, 1] }],
      total_pot: 15,
      to_act: 0,
      turn_id: 'turn-hu',
      turn_started_at: now() - 3,
      turn_deadline_at: now() + 17,
      next_hand_at: null,
      seats,
      legal: {
        seat: 0,
        to_call: 5,
        can_fold: true,
        can_check: false,
        can_call: true,
        call_amount: 5,
        raise_kind: 'raise',
        min_to: 20,
        max_to: 1450,
        all_in_to: 1450,
        stack: 1450,
        current_bet: 10,
        committed: 10
      },
      log: [
        { type: 'hand_start', hand_no: 19 },
        { type: 'blinds' },
        { seat: 1, type: 'action', kind: 'raise', to: 10 }
      ],
      last_hand: null,
      settings: { decision_timeout_s: 20, next_hand_delay_s: 4, chatter: true }
    }
  })(),

  backend_error: {
    __isError: true
  },
  backend_missing: {
    __isError: true
  }
}

export const MODELS_FIXTURE = {
  options: [
    { id: 'default', label: 'Your default model', provider: 'hermes', model: 'default' },
    { id: 'hermes-4-405b', label: 'hermes-4-405b', provider: 'hermes', model: 'hermes-4-405b' },
    { id: 'hermes-4-70b', label: 'hermes-4-70b', provider: 'hermes', model: 'hermes-4-70b' },
    { id: 'local', label: 'Local model', provider: 'local', model: 'llama-3.3-70b' }
  ],
  default_id: 'default'
}

export const PROFILES_FIXTURE = {
  profiles: [
    { id: 'developer', name: 'Developer', label: 'Developer (developer)', avatar: { image: null, shape: 'blobatar::triangle', color: '#8b5cf6', seed: 'developer' }, model: 'fixture-model-1', provider: 'openai-codex' },
    { id: 'design', name: 'Design', label: 'Design (design)', avatar: { image: null, shape: 'blobatar', color: '#a855f7', seed: 'design' }, model: 'fixture-model-2', provider: 'openai-codex' },
    { id: 'frontend', name: 'Frontend', label: 'Frontend (frontend)', avatar: { image: null, shape: 'squircle', color: '#4f79ed', seed: 'frontend' }, model: 'fixture-model-3', provider: 'openai-codex' },
    { id: 'researcher', name: 'Researcher', label: 'Researcher (researcher)', avatar: { image: null, shape: 'blobatar::cloud', color: '#4eafbd', seed: 'researcher' }, model: 'fixture-model-4', provider: 'openai-codex' }
  ]
}
